[package]
name = "cosmic-session"
description = "The session manager for the COSMIC desktop environment"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"
authors = ["Lucy <lucy@system76.com>"]
publish = false

[dependencies]
color-eyre = "0.6.1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
